### ISSUE TITLE
No python file to build, abort

### ISSUE THREAD

**Issue by bulingda** [huntzhan/pywhlobf#2]
```
[root@localhost dist]# pywhlobf xx-0.1.0-py3-none-any.whl ./tmp
[INFO] Processing xx-0.1.0-py3-none-any.whl...
[INFO] input_whl=xx-0.1.0-py3-none-any.whl
[INFO] distribution=xx, version=0.1.0, build_tag=None
[INFO] extract_folder=/tmp/tmpg9_34b_h
[INFO] No python file to build, abort.
[INFO]
```
May I ask what document is missing?

**Comment by huntzhan** [comment]
The log indicates there's no python files in your wheel.

https://github.com/huntzhan/pywhlobf/blob/14d46b599f0d4c9ac7a1484a215bfb6d75ff4ef7/pywhlobf/cli.py#L51-L54
https://github.com/huntzhan/pywhlobf/blob/14d46b599f0d4c9ac7a1484a215bfb6d75ff4ef7/pywhlobf/prep.py#L38-L43

**Comment by huntzhan** [comment]
feel free to reopen this issue.
