### ISSUE TITLE
Tool generates incorrect platform tag in output filename when run on Linux when using wheel version >0.34.2

### ISSUE THREAD

**Issue by hutchisr** [huntzhan/pywhlobf#4]
pywhlobf currently (as of 0.2.3) generates an uninstallable wheel on linux due to an error in the platform tag in the output filename:

As an example:

Running `pywhlobf test-0.1.0-py3-none-any.whl dist` will produce the output `dist/test-0.1.0-cp38-cp38-linux-x86_64.whl`. Attempting to run `pip3.8 install dist/test-0.1.0-cp38-cp38-linux-x86_64.whl` will produce the error `ERROR: test-0.1.0-cp38-cp38-linux-x86_64.whl is not a supported wheel on this platform.` because `linux-x86_64` is not a valid platform tag, it should be `linux_x86_64` (note the use of an underscore rather than a dash). Manually renaming the file to the correct pattern solves the issue.

This seems to be related to changes in `wheel.bdist_wheel.get_platform` in versions 0.35.0 and above.

Related: https://github.com/huntzhan/pywhlobf/issues/1

**Comment by huntzhan** [comment]
investigating

**Comment by huntzhan** [comment]
@hutchisr pls help verify this issue has been resolved. feel free to re-open if something is still wrong.
